const fieldMap = [
  { key: 'templetCode', label: '模板编号', flag: true },
  { key: 'templetName', label: '模板名称', flag: true },
  { key: 'price', label: '优惠券金额', flag: true },
  { key: 'total', label: '总数量', flag: true },
  { key: 'couponType', label: '优惠券类别', flag: true },
  { key: 'isInter', label: '国际/国内', flag: true },
  { key: 'startFdate', label: '航班日期开始', flag: false },
  { key: 'endFdate', label: '航班日期结束', flag: false },
  { key: 'condition', label: '限制条件', flag: true },
  { key: 'authCheck', label: '是否实名认证', flag: true },
  { key: 'isReturn', label: '取消返券', flag: true },
  { key: 'templetStatus', label: '启用状态', flag: true },
  { key: 'fdateDisable', label: '排除航班日期范围', flag: false },
  { key: 'afrom', label: '起飞地', flag: false },
  { key: 'ato', label: '到达地', flag: false },
  { key: 'fnumber', label: '航班号', flag: false },
  { key: 'fnumberDisable', label: '排除航班号', flag: false },
  { key: 'cabin', label: '舱位', flag: false },
  { key: 'cabinDisable', label: '排除舱位', flag: false },
  { key: 'highestPrice', label: '票价上限', flag: false },
  { key: 'lowestPrice', label: '票价下限', flag: false },
  { key: 'validityType', label: '有效期类型', flag: true },
  { key: 'validityStart', label: '有效日期起', flag: false },
  { key: 'validityDisable', label: '排除有效日期段', flag: false },
  { key: 'payMethod', label: '支付方式限制', flag: false },
  { key: 'payLimit', label: '支付时限', flag: false },
  { key: 'shareFlag', label: '是否支持共享航班', flag: false },
  { key: 'validityEnd', label: '有效日期止', flag: false },
  { key: 'sailType', label: '优惠类型', flag: true },
  { key: 'validityDay', label: '天数', flag: false },
  { key: 'createTime', label: '创建时间', flag: false },
  { key: 'successNum', label: '已发放数量', flag: false },
  { key: 'createOpName', label: '创建人姓名', flag: false }
]
export default fieldMap
