const fieldMap = [
  { key: 'ruleCode', label: '批次号', flag: true },
  { key: 'flightno', label: '航班号', flag: true },
  { key: 'departureAirport', label: '出发城市', flag: true },
  { key: 'arrivalAirport', label: '到达城市', flag: true },
  { key: 'operatingcarrier', label: '承运方', flag: true },
  { key: 'marketcarrier', label: '市场方', flag: true },
  { key: 'saleBeginTime', label: '销售开始日期', flag: true },
  { key: 'saleEndTime', label: '销售截止日期', flag: true },
  { key: 'flightBeginDate', label: '航班开始', flag: true },
  { key: 'flightEndDate', label: '航班截止', flag: true },
  { key: 'fdateDisable', label: '排除航班日期段', flag: true },
  { key: 'cabin', label: '舱位', flag: true },
  { key: 'channel', label: '渠道编号', flag: false },
  { key: 'discountType', label: '折扣类型', flag: true },
  { key: 'actyTag', label: '活动标签', flag: false },
  { key: 'actyId', label: '关联活动', flag: false },
  { key: 'discountDirection', label: '折扣', flag: true },
  { key: 'discountValue', label: '具体值', flag: true },
  { key: 'applyFreightType', label: '运价类型', flag: true },
  { key: 'effectivePeople', label: '生效人群', flag: false },
  { key: 'createDate', label: '创建时间', flag: false },
  { key: 'createOpid', label: '创建人', flag: false },
  { key: 'modifyDate', label: '修改时间', flag: false },
  { key: 'modifyOpid', label: '修改人', flag: false },
  { key: 'weekLimit', label: '航班周期', flag: false },
  { key: 'flightnoDisable', label: '排除航班号', flag: false },
  { key: 'policyId', label: '小星星编号', flag: true}
  // { key: 'createDate', label: '创建时间' },
  // { key: 'createOpName', label: '创建人' },
  // { key: 'modifyDate', label: '修改时间' },
  // { key: 'modifyOpName', label: '修改人' },
  // { key: 'remark', label: '备注' },
  // { key: 'ruleStatus', label: '启用/禁用' }
]
export default fieldMap
