const fieldMap = [
  { key: 'pname', label: '乘机人', flag: true },
  { key: 'pnr', label: 'pnr', flag: true },
  { key: 'airways', label: '市场方', flag: false },
  { key: 'airline', label: '承运方', flag: false },
  { key: 'channel', label: '渠道类型', flag: true },
  { key: 'ordercode', label: '订单编号', flag: false },
  { key: 'flightSegment', label: '航段', flag: true },
  { key: 'productname', label: '产品名称', flag: false },
  { key: 'flyDate', label: '航班日期', flag: true },
  { key: 'flyTime', label: '起飞时间', flag: false },
  { key: 'arriveTime', label: '到达时间', flag: false },
  { key: 'cabin', label: '舱位', flag: false },
  { key: 'fare', label: '票面价', flag: false },
  { key: 'airportTax', label: '机建', flag: false },
  { key: 'fuelTax', label: '燃油', flag: false },
  { key: 'unexpInsr', label: '航意险', flag: false },
  { key: 'delayInsr', label: '航延险', flag: false },
  { key: 'allpjrfare', label: '票面总款', flag: false },
  { key: 'productMoney', label: '附加商品金额', flag: false },
  { key: 'integralFare', label: '积分价', flag: false },
  { key: 'fmoney', label: '优惠金额', flag: false },
  { key: 'sjfare', label: '实际票款', flag: true },
  { key: 'ticStatus', label: '客票状态', flag: false },
  { key: 'refundNo', label: '退票单号', flag: false },
  { key: 'state', label: '退改状态', flag: false },
  // { key: 'refundType', label: '退票来源', flag: false },
  { key: 'eticketno', label: '机票号', flag: true },
  //  默认展示
  { key: 'flightNo', label: '航班号', flag: true },
  { key: 'printFlag', label: '行程单是否需回收', flag: false },
  { key: 'walletMoney', label: '红包金额', flag: false },
  { key: 'epidemicInsr', label: '疫情隔离险', flag: false },
  { key: 'refundTicketInsr', label: '航空退票险', flag: false }
]
export default fieldMap
