const fieldMap = [
  { key: 'upgradCode', label: '产品编码' },
  { key: 'upgradName', label: '产品名称' },
  { key: 'policyCode', label: '规则批号' },
  { key: 'channelpgradCode', label: '产品编码' },
  { key: 'channel', label: '渠道编号' },
  { key: 'flightNo', label: '航班号' },
  { key: 'sailFrom', label: '出发地' },
  { key: 'sailTo', label: '到达地' },
  { key: 'tripType', label: '航程类型' },
  { key: 'sellStartTime', label: '销售起始时间' },
  { key: 'sellEndTime', label: '销售截止时间' },
  { key: 'flightDateStart', label: '航班起始日期' },
  { key: 'flightDateEnd', label: '航班截止日期' },
  { key: 'isinter', label: '国内/国际' },
  { key: 'policyCabin', label: '适用可升舱舱位' },
  { key: 'fareType', label: '运价类型' },
  { key: 'adtFare', label: '成人升舱价格' },
  { key: 'chdFare', label: '儿童升舱价格' },
  { key: 'infFare', label: '婴儿升舱价格' },
  { key: 'createDate', label: '创建时间' },
  { key: 'createOpName', label: '创建人' },
  { key: 'modifyDate', label: '修改时间' },
  { key: 'modifyOpName', label: '修改人' },
  { key: 'policyRemark', label: '备注' }
]
export default fieldMap
