const fieldMap = [
  { key: 'ruleCode', label: '批次号', flag: true },
  { key: 'channel', label: '生效渠道', flag: true },
  { key: 'route', label: '航线', flag: true },
  { key: 'aircode', label: '航空公司', flag: true },
  { key: 'fbc', label: '票价级别', flag: true },
  { key: 'airtype', label: '航程类型', flag: true },
  { key: 'cabin', label: '舱位', flag: true },
  { key: 'timeLimit', label: '计划离站时间前', flag: true },
  { key: 'saleStartTime', label: '销售起始日', flag: false },
  { key: 'saleEndTime', label: '销售截止日', flag: false },
  { key: 'flightStartTime', label: '航班起始日期', flag: false },
  { key: 'flightEndTime', label: '航班截止日期', flag: false },
  { key: 'currency', label: '币种', flag: true },
  { key: 'befreFee', label: '计划离站时间前退票手续费', flag: false },
  { key: 'afterFee', label: '计划离站时间后退票手续费', flag: false },
  { key: 'noshowfee', label: '误机费', flag: false },
  { key: 'partsusefee', label: '部分使用退票费', flag: false },
  { key: 'standard', label: '舱位标准价', flag: false },
  { key: 'isrefundtax', label: '燃油是否可退', flag: false },
  { key: 'consignmentWeight', label: '托运行李额', flag: false },
  { key: 'selfWeight', label: '自提行李额', flag: false },
  { key: 'iscanchange', label: '是否可变更', flag: false },
  { key: 'createDate', label: '创建时间', flag: false },
  { key: 'createOpid', label: '创建人', flag: false },
  { key: 'modifyDate', label: '修改时间', flag: false },
  { key: 'modifyOpid', label: '修改人', flag: false }
]
export default fieldMap
