const fieldMap = [
  { key: 'receiveName', label: '领用规则名称', flag: true },
  { key: 'receiveCode', label: '领用规则编号', flag: true },
  { key: 'activityCode', label: '活动编号', flag: true },
  { key: 'activityName', label: '活动名称', flag: true },
  { key: 'channel', label: '领用渠道', flag: true },
  { key: 'totalNum', label: '参与数目', flag: true },
  { key: 'saleType', label: '优惠类型', flag: true },
  { key: 'templetName', label: '模板名称', flag: false },
  { key: 'receiveType', label: '领取类型', flag: true },
  { key: 'intervalTime', label: '间隔时间', flag: false },
  { key: 'channelNum', label: '渠道数量限制', flag: false },
  { key: 'channelMoney', label: '渠道金额限制', flag: false },
  { key: 'startFdate', label: '航班日期开始', flag: false },
  { key: 'endFdtae', label: '航班日期结束', flag: false },
  { key: 'fdateDisable', label: '排除航班日期', flag: false },
  { key: 'afrom', label: '适用出发地', flag: false },
  { key: 'ato', label: '适用目的地', flag: false },
  { key: 'flightNo', label: '适用航班号', flag: false },
  { key: 'cabin', label: '适用舱位', flag: false },
  { key: 'cabinDisable', label: '排除适用舱位', flag: false },
  { key: 'pmPriceLimitUp', label: '票价上限', flag: false },
  { key: 'pmPriceLimitDown', label: '票价下限', flag: false },
  { key: 'authCheck', label: '是否实名认证', flag: false },
  { key: 'ffpCheck', label: '是否常旅客', flag: false },
  { key: 'ffpLevel', label: '常旅客级别', flag: false },
  { key: 'payMethod', label: '支付方式限制', flag: false },
  { key: 'receiveRemark', label: '领用备注', flag: false },
  { key: 'receiveNotice', label: '领取通知', flag: true },
  { key: 'receiveStatus', label: '启用状态', flag: true },
  { key: 'createTime', label: '创建时间', flag: false },
  { key: 'productid', label: '领取产品标识', flag: false },
  { key: 'applyCount', label: '领取数量', flag: false },
  { key: 'createOpName', label: '创建人姓名', flag: false }

]
export default fieldMap
